# -*- coding: utf-8 -*-
"""Untitled2.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1SA_lC6XCJV91BrQ8GIO8uRMd-nJc6Hws
"""

print('abcd', end=" ")
print('efgh', end=" ")
print('ijkl')

pi=1.2345567
print("%.2f" %pi)

when = '저녁'
where = "집"

print(f"나는 {when}시에 {where}에 간다")

when="오늘"
where="집에서"
why="깨어나기 위해"

print(f'새싹들은 {when} 각자의 {where} {why} 열심히 코딩을 했다.')

a = 10
b = 2

print(a + b)
print(a - b)
print(a * b)
print(a / b)
print(a % b)

a = 10
b = 2

print(a % b)

#if a % 2 == 0:
#if a 5 2 ==! 0:

print(a//b)
print('---------------')
a=11
print(a//b)

num = int(input("3"))
print(f'{num}단')
print(f'{num} x 1 = {num*1}')
print(f'{num} x 2 = {num*2}')
print(f'{num} x 3 = {num*3}')
print(f'{num} x 4 = {num*4}')
print(f'{num} x 5 = {num*5}')

list_1 = [1,2,3,4,5,6,7,8,9,10]
# if와 elif가 조건이 둘다 맞으면, if우선 실행, elif실행 안됨
if sum(list_1) > 100:
    print("List_1의 합은 ")
elif sum(list_1) > 70:
    print("이것도 안됨")
else:
    print("된다")

List_3 = [1,2,3]
if len(list_3) < 10:
    print("list_3:", list_3)

list_1 = [1,2,3,4,5,6,7,8,9]

 while len(list_1) > 1:
     print(list_1.pop())
print(list_1)

n = 10 
while n > 0:
      print ('n : ', n)
      n = n-1

      if n ==5:
        break
